"""
dashboard/routes/auth.py
Weir — Magic-link authentication via Supabase.

Flow:
  1. User submits email → POST /auth/login → Supabase sends magic link
  2. User clicks link → Supabase redirects to /auth/callback with token in URL hash
  3. JS on callback page extracts hash token → redirects to /auth/session?access_token=...
  4. /auth/session decodes JWT email, upserts user row, signs email|api_key cookie → redirect to /
"""

import base64
import json
import logging
import os

import aiohttp
from dotenv import load_dotenv
from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.templating import Jinja2Templates
from itsdangerous import TimestampSigner

load_dotenv()

log = logging.getLogger("weir.auth")
router = APIRouter()
templates = Jinja2Templates(directory="templates")

SUPABASE_URL = os.getenv("WEIR_SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("WEIR_SUPABASE_KEY", "")   # anon key — only used to send magic link
SERVICE_KEY  = os.getenv("WEIR_SERVICE_KEY", "")    # service_role — used for user upsert
SECRET_KEY   = os.getenv("WEIR_SECRET_KEY", "dev-secret-change-me")
SESSION_COOKIE = "weir_session"
SESSION_MAX_AGE = 604800  # 7 days


def _svc_headers(prefer_repr: bool = False) -> dict:
    h = {
        "apikey": SERVICE_KEY,
        "Authorization": f"Bearer {SERVICE_KEY}",
        "Content-Type": "application/json",
    }
    if prefer_repr:
        h["Prefer"] = "return=representation"
    return h


def _sign_session(email: str, api_key: str) -> str:
    """Sign 'email|api_key' into a tamper-proof cookie value."""
    signer = TimestampSigner(SECRET_KEY, sep="~")
    return signer.sign(f"{email}|{api_key}".encode()).decode()


def _decode_jwt_email(token: str) -> str:
    """Decode email from a Supabase JWT without verification (we trust Supabase delivery)."""
    try:
        payload_b64 = token.split(".")[1]
        payload_b64 += "=" * (4 - len(payload_b64) % 4)
        payload = json.loads(base64.urlsafe_b64decode(payload_b64))
        return payload.get("email", "")
    except Exception:
        return ""


async def _upsert_user(email: str) -> str:
    """
    Look up the user row by email. Create it if it doesn't exist.
    Returns the api_key string, or "" on failure.
    """
    async with aiohttp.ClientSession() as session:
        # GET existing user
        url = f"{SUPABASE_URL}/rest/v1/users?email=eq.{email}&select=id,api_key&limit=1"
        try:
            async with session.get(url, headers=_svc_headers()) as resp:
                if resp.status == 200:
                    rows = await resp.json()
                    if rows:
                        return rows[0]["api_key"]
        except Exception as exc:
            log.error("User lookup failed: %s", exc)
            return ""

        # POST new user — api_key generated by Supabase DEFAULT
        try:
            async with session.post(
                f"{SUPABASE_URL}/rest/v1/users",
                headers=_svc_headers(prefer_repr=True),
                json={"email": email},
            ) as resp:
                if resp.status in (200, 201):
                    rows = await resp.json()
                    if rows:
                        log.info("Created new user: %s", email)
                        return rows[0]["api_key"]
                body = await resp.text()
                log.error("User create returned %d: %s", resp.status, body[:200])
        except Exception as exc:
            log.error("User create failed: %s", exc)

    return ""


def _set_session_cookie(response: RedirectResponse, email: str, api_key: str) -> None:
    signed = _sign_session(email, api_key)
    response.set_cookie(
        SESSION_COOKIE,
        signed,
        httponly=True,
        samesite="lax",
        max_age=SESSION_MAX_AGE,
    )


# ── Routes ───────────────────────────────────────────────────────────────────

@router.get("/login")
async def login_page(request: Request):
    return templates.TemplateResponse("login.html", {"request": request})


@router.post("/auth/login")
async def send_magic_link(request: Request):
    form = await request.form()
    email = str(form.get("email", "")).strip()

    if not email:
        return HTMLResponse('<p class="auth-error">Please enter a valid email address.</p>')

    base_url = str(request.base_url).rstrip("/")
    redirect_to = f"{base_url}/auth/callback"

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"{SUPABASE_URL}/auth/v1/magiclink",
                headers={"apikey": SUPABASE_KEY, "Content-Type": "application/json"},
                json={"email": email, "options": {"emailRedirectTo": redirect_to}},
            ) as resp:
                if resp.status not in (200, 204):
                    body = await resp.text()
                    return HTMLResponse(f'<p class="auth-error">Supabase error: {body[:120]}</p>')
    except Exception as exc:
        return HTMLResponse(f'<p class="auth-error">Could not reach Supabase: {exc}</p>')

    return HTMLResponse(
        '<p class="auth-success">Magic link sent — check your email.</p>'
    )


@router.get("/auth/callback")
async def auth_callback(
    request: Request,
    code: str = "",
    token_hash: str = "",
    type: str = "",
):
    # Path 1: REST API magic link — token_hash + type
    if token_hash and type:
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{SUPABASE_URL}/auth/v1/verify",
                    headers={"apikey": SUPABASE_KEY, "Content-Type": "application/json"},
                    json={"token_hash": token_hash, "type": type},
                ) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        email = _decode_jwt_email(data.get("access_token", ""))
                        if email:
                            api_key = await _upsert_user(email)
                            response = RedirectResponse("/", status_code=302)
                            _set_session_cookie(response, email, api_key)
                            return response
        except Exception:
            pass
        return RedirectResponse("/login", status_code=302)

    # Path 2: PKCE code exchange
    if code:
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{SUPABASE_URL}/auth/v1/token?grant_type=pkce",
                    headers={"apikey": SUPABASE_KEY, "Content-Type": "application/json"},
                    json={"auth_code": code},
                ) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        email = _decode_jwt_email(data.get("access_token", ""))
                        if email:
                            api_key = await _upsert_user(email)
                            response = RedirectResponse("/", status_code=302)
                            _set_session_cookie(response, email, api_key)
                            return response
        except Exception:
            pass
        return RedirectResponse("/login", status_code=302)

    # Path 3: Hash-fragment fallback (legacy Supabase flow)
    return HTMLResponse("""
<!doctype html><html><head><title>Signing in…</title></head><body>
<script>
  const hash = window.location.hash.slice(1);
  const params = new URLSearchParams(hash);
  const token = params.get("access_token");
  if (token) {
    window.location.href = "/auth/session?access_token=" + encodeURIComponent(token);
  } else {
    window.location.href = "/login";
  }
</script>
<p>Signing you in…</p>
</body></html>
""")


@router.get("/auth/session")
async def create_session(request: Request, access_token: str = ""):
    email = _decode_jwt_email(access_token)
    if not email:
        return RedirectResponse("/login", status_code=302)

    api_key = await _upsert_user(email)
    response = RedirectResponse("/", status_code=302)
    _set_session_cookie(response, email, api_key)
    return response


@router.get("/auth/logout")
async def logout():
    response = RedirectResponse("/login", status_code=302)
    response.delete_cookie(SESSION_COOKIE)
    return response

